### ISSUE TITLE
Using python 3.6 

### ISSUE THREAD

**Issue by xuesoso** [chanzuckerberg/ExpressionMatrix2#19]
Hi Paolo, I was wondering if there is support for using python 3.6? Currently, I run into this issue when I try to run "python run.py"

Traceback (most recent call last):
  File "ExpressionMatrix2-0.4.0/tests/ToyTest1/run.py", line 4, in <module>
    import ExpressionMatrix2 
ImportError: Python version mismatch: module was compiled for version 3.5, while the interpreter is running version 3.6.

**Comment by paoloczi** [comment]
You can use Python 3.6, and I know of a group of users that are doing just that, but you would have to build your code from source. There are directions here for that:

https://chanzuckerberg.github.io/ExpressionMatrix2/doc/Building.html

However, to make your life easier I can consider adding to the next release a pre-built version for your platform and environment. What Linux distribution are you using?

**Comment by xuesoso** [comment]
Thanks! I'm currently using ubuntu 16.04.

**Comment by paoloczi** [comment]
I am also on ubuntu 16.04, but I get:

python3 --version
Python 3.5.2

This is what I get after installing ubuntu package "python3" from the default repositories. Do you have a customized Python installation?

**Comment by paoloczi** [comment]
For example, this askubuntu entry

https://askubuntu.com/questions/865554/how-do-i-install-python-3-6-using-apt-get

says that you need to do something special and use a non-standard repository to get Python 3.6 on ubuntu 16.04. However, it becomes available from the standard repositories on Ubuntu 16.10 and 17.04, and becomes the default on Ubuntu 17.10. Can you check if you really have Ubuntu 16.04? You can use this command:

lsb_release -a

**Comment by xuesoso** [comment]
Yes, I forgot to mention that I'm using a custom python 3.6.4 distributed by anaconda (64-bit) on ubuntu 16.04.3 LTS. 
Output from "python --version"
Python 3.6.4 :: Anaconda custom (64-bit)

**Comment by paoloczi** [comment]
Since this is a non-standard configuration I will not add it to the release package, but I could do one of two things for you:

1. Help you build it from source - it's pretty easy if you are on ubuntu 16, and directions are here https://chanzuckerberg.github.io/ExpressionMatrix2/doc/Building.html
You could try and tell me where you get stuck and I can help you out.
2. If you are not comfortable building it from source, I could build it for you. I would have to create a virtual machine that replicates your environment. For that, you would have to tell me how you installed Anaconda and the custom Python.

**Comment by xuesoso** [comment]
Thanks Paolo,
I first went ahead to install all the dependencies listed on your documentation:
1. libhdf5-10
2. libhdf5-cpp-11
3. python3-all-dev 
4. pybind11 (under /home/user/anaconda3/lib/python3.6/site-packages)

Then I created and cd'ed into a new directory for the build. I ran the following command on terminal with no error:
`cmake -DPYTHON_INCLUDE_PATH=/home/user/anaconda3/bin/python3.6m -DPYBIND11_INCLUDE_PATH=/home/user/anaconda3/lib/python3.6/site-packages /media/dataStore1/Tools/Paoloczi/ExpressionMatrix2/src/`

Then I ran `make`, but it threw me this error:
[ 28%] Building CXX object CMakeFiles/ExpressionMatrix2.dir/ExpressionMatrixHdf5.cpp.o
/usr/bin/c++   -I/home/user/anaconda3/bin/python3.6m -I/home/user/anaconda3/lib/python3.6/site-packages -I/usr/include/hdf5/serial  -fPIC   -std=c++0x -ggdb3 -O3 -msse4.2 -Wall -Wconversion -Wno-unused-result -o CMakeFiles/ExpressionMatrix2.dir/ExpressionMatrixHdf5.cpp.o -c /media/dataStore1/Tools/Paoloczi/ExpressionMatrix2/src/ExpressionMatrixHdf5.cpp
cc1plus: warning: /home/user/anaconda3/bin/python3.6m: not a directory
In file included from /media/dataStore1/Tools/Paoloczi/ExpressionMatrix2/src/ExpressionMatrixHdf5.cpp:6:0:
/media/dataStore1/Tools/Paoloczi/ExpressionMatrix2/src/hdf5.hpp:57:19: fatal error: H5Cpp.h: No such file or directory
compilation terminated.
CMakeFiles/ExpressionMatrix2.dir/build.make:353: recipe for target 'CMakeFiles/ExpressionMatrix2.dir/ExpressionMatrixHdf5.cpp.o' failed
make[2]: *** [CMakeFiles/ExpressionMatrix2.dir/ExpressionMatrixHdf5.cpp.o] Error 1
make[2]: Leaving directory '/media/dataStore1/Tools/Paoloczi/ExpressionMatrix2/ExpressionMatrix2_build'
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/ExpressionMatrix2.dir/all' failed
make[1]: *** [CMakeFiles/ExpressionMatrix2.dir/all] Error 2
make[1]: Leaving directory '/media/dataStore1/Tools/Paoloczi/ExpressionMatrix2/ExpressionMatrix2_build'
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by paoloczi** [comment]
As the "Prerequisites" section in the documentation says, to build from source you need package libhdf5-dev. You installed libhdf5-10 which is sufficient for running but not for building.

Also: you have a warning that says "cc1plus: warning: /home/user/anaconda3/bin/python3.6m: not a directory". Does this directory exist? Does it contain the Python include files (files "*.h")?

To make your life easier, I suggest that you build without HDF5 functionality, at least for your first build. Restart from scratch from a clean directory, adding "-DBUILD_WITH_HDF5=OFF" to the arguments for the cmake command. HDF5 functionality is only needed to read HDF5 files from the 10X genomics pipeline. If your input files are comma- or tab-separated files, you don't need it. If you turn it off, none of the HDF5 packages will be needed.

**Comment by xuesoso** [comment]
Thanks Paolo, I successfully built and ran it. I fixed the errors: I installed libhdf5-dev, and changed the python path to its correct directory under anaconda distribution (-DPYTHON_INCLUDE_PATH=/home/soso/anaconda3/include/python3.6m).

**Comment by paoloczi** [comment]
All right, cool, congratulations! Feel free to create other issues if you bump into problems and/or you want to propose enhancements.
