### ISSUE TITLE
Is there any published paper?

### ISSUE THREAD

**Issue by BIOINSu** [chanzuckerberg/ExpressionMatrix2#20]
Dear authors,
This is a very great job. Is there any publicly published paper to understand the process of clustering with LSH in more detail? Thanks a lot.

**Comment by paoloczi** [comment]
Thank you. This work is not being pursued or developed. The code is released under an MIT license, which gives you ample flexibility, and your are certainly free to publish the methods in your name, if you so chose. You can optionally include a citation to this GitHub repository, but that is not required.

**Comment by BIOINSu** [comment]
I see. Thanks a lot. Issue close.
