### ISSUE TITLE
Create cell set using numerical cell meta data

### ISSUE THREAD

**Issue by paoloczi** [chanzuckerberg/ExpressionMatrix2#5]
I implemented this as follows:
createCellSetUsingNumericMetaDataGreaterThan(cellSetName, metaDataName, lowerBound)
createCellSetUsingNumericMetaDataLessThan(cellSetName, metaDataName, upperBound) 
createCellSetUsingNumericMetaDataBetween(cellSetName, metaDataName, lowerBound, upperBound) 

Charlotte, please close after verifying that it satisfied your needs.

**Comment by csweaver** [comment]
Yes, this is working as expected.
